const types={url:['Website URL','https://example.com'],text:['Your text','Write your message...'],phone:['Phone number','+1 555 123 4567'],whatsapp:['WhatsApp number','15551234567'],wifi:null,email:null,sms:null,vcard:null,location:null};let type='url',last='';
function $(x){return document.getElementById(x)}
function render(){let h='';if(['url','text','phone','whatsapp'].includes(type))h=`<label>Information</label><input id="main" placeholder="${types[type][1]}">`;else{const map={wifi:[['ssid','Network name'],['password','Password']],email:[['email','Email address'],['subject','Subject'],['body','Message']],sms:[['phone','Phone number'],['message','Message']],vcard:[['name','Full name'],['phone','Phone'],['email','Email'],['company','Company']],location:[['lat','Latitude'],['lng','Longitude']]};h=map[type].map(x=>`<label>${x[1]}</label><input id="f-${x[0]}" placeholder="${x[1]}">`).join('')}$('fields').innerHTML=h}
function val(){const g=k=>document.getElementById('f-'+k)?.value||'';if(['url','text','phone','whatsapp'].includes(type))return $('main').value.trim();if(type==='wifi')return `WIFI:T:WPA;S:${g('ssid')};P:${g('password')};;`;if(type==='email')return `mailto:${g('email')}?subject=${encodeURIComponent(g('subject'))}&body=${encodeURIComponent(g('body'))}`;if(type==='sms')return `SMSTO:${g('phone')}:${g('message')}`;if(type==='vcard')return `BEGIN:VCARD\nVERSION:3.0\nFN:${g('name')}\nTEL:${g('phone')}\nEMAIL:${g('email')}\nORG:${g('company')}\nEND:VCARD`;return `geo:${g('lat')},${g('lng')}`}
function gen(){const d=val();$('err').textContent='';if(!d){$('err').textContent='Please enter your information.';return}QRCode.toCanvas($('canvas'),d,{width:+$('size').value,margin:2,errorCorrectionLevel:$('ecc').value,color:{dark:$('fg').value,light:$('transparent').checked?'#00000000':$('bg').value}},e=>{if(e)$('err').textContent='Could not generate QR';else{$('empty').style.display='none';last=d}})}
document.querySelectorAll('#types button').forEach(b=>b.onclick=()=>{document.querySelectorAll('#types button').forEach(x=>x.classList.remove('active'));b.classList.add('active');type=b.dataset.t;render();gen()});
$('gen').onclick=gen;['fg','bg','size','ecc','transparent'].forEach(x=>$(x).oninput=gen);
$('png').onclick=()=>{if(!last)return gen();const a=document.createElement('a');a.href=$('canvas').toDataURL('image/png');a.download='qrforge.png';a.click()};
$('svg').onclick=()=>{if(!last)return gen();QRCode.toString(last,{type:'svg',width:+$('size').value,margin:2,errorCorrectionLevel:$('ecc').value,color:{dark:$('fg').value,light:$('transparent').checked?'#00000000':$('bg').value}},(e,s)=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([s],{type:'image/svg+xml'}));a.download='qrforge.svg';a.click()})};
$('save').onclick=async()=>{const token=localStorage.token;if(!token)return location.href='/login.html?save=1';const r=await fetch('/api/qrs',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+token},body:JSON.stringify({type,name:'My '+type+' QR',data:last||val(),dynamic:false})});alert(r.ok?'Saved to your dashboard':'Could not save')};
$('theme').onclick=()=>{document.body.classList.toggle('dark');localStorage.dark=document.body.classList.contains('dark')};
if(localStorage.dark==='true')document.body.classList.add('dark');render();QRCode.toCanvas($('heroQR'),'https://example.com',{width:210,margin:2,color:{dark:'#635bff',light:'#fff'}});